### ISSUE TITLE
[Bug]: Always spawn on backup point

### ISSUE THREAD

**Issue by IzPogo** [Flamtky/fivem-respawn-nearby#10]
### Game Version

3258

### Problem Description

For some reason this just doesn't work for me. When I die I didn't respawn at all so I'm guessing the resource was not even doing anything in the first place.

### Steps to Reproduce

1. Placed the resource in the resource folder.
2. Ensured it after spawnmanager.
3. Got into server, unalived self.
4. Mentioned problem happened.

### Expected Behavior

Expected for myself to respawn in the first place, perhaps somewhere nearby.

### Actual Behavior

Didn't respawn, character was frozen in place with camera being stuck too. Couldn't open the pause menu so that includes the map. Interaction-like menus such as vMenu couldn't be open as well. Otherwise the game was still alive with peds and cars moving around so not a crash.

![Screenshot 2024-09-27 213500](https://github.com/user-attachments/assets/cc6a18e4-4a0b-44a4-99b1-04be9ba75489)

### Console Output

```shell
## Nothing is on the console since the resource didn't work for me to begin with.
```

### Server.cfg

```shell
## These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure nearby-respawn
ensure sessionmanager
## ensure basic-gamemode
ensure hardcap
ensure vMenu
ensure simple_loading_screen

## (basic-gamemode commented out due to this resource being a "gamemode" type already)
```

### Additional Context

Debug blips also didn't work, nothing was on the map when alive and I couldn't even open the map when I died.

**Comment by Flamtky** [comment]
@IzPogo 
Thanks for the report.
> Game Version
3258

I didn't test my script with version 3258, but I think it should make no difference. I will test it on that version for you.

> Console Output
Nothing is on the console since the resource didn't work for me to begin with.

It sounds weird that the script is not working at all, and there are no errors in the console. It almost sounds like the resource didn't start. Please check the server log to see if the resource did start or not.

Maybe the resource did not install correctly? Check the installation guide in the [README.md](https://github.com/Flamtky/fivem-respawn-nearby/blob/main/README.md).

**Comment by IzPogo** [comment]
@Flamtky  thank you, hopefully it doesn't have anything to do with the specific version as I would like to use the Dollar Bounty stuff.

> Please check the server log to see if the resource did start or not.

As you can see, it did start and was right below spawnmanager.
```
resources] Started resource spawnmanager
[   script:mapmanager] [0mStarted gametype Freeroam
[           resources] Started resource fivem-respawn-nearby
```
At first, I just left the name as fivem-respawn-nearby as that's what it downloaded as. Later attempts I changed it to 'nearby-respawn' as to follow the instructions. Same thing happened.
```
resources] Started resource spawnmanager
[   script:mapmanager] [97mStarted gametype Freeroam
[           resources] Started resource nearby-respawn
```

I will try to start my server with no additional resources other than this one and see if it's actually because of a conflict, which would be odd as none of the other resources I use interferes with spawning mechanics.

I will get back to you, thanks again for your time.

**Comment by IzPogo** [comment]
Little update,
> I will try to start my server with no additional resources other than this one and see if it's actually because of a conflict

Did this and it unfortunately didn't work, still.

Though I forgot to provide you with this information.
![Screenshot 2024-09-28 144021](https://github.com/user-attachments/assets/c743be78-725f-4d98-8c11-5bfff8916dcd)
When I joined my server during my numerous attempts, I would spawn on the backup point, which was the default (0,0,70). So it means the resource does work for me.....but only to an extent. 

Hopefully this may help you in figuring out what's wrong on whoever's end.

**Comment by Flamtky** [comment]
Hi @IzPogo,

I couldn't reproduce the error on my end. I've updated my local dev server to version 3258, and it works fine. Additionally, I made some small logic changes and updated the whole code base, which might have resolved your issue. Could you please check the [`dev`](https://github.com/Flamtky/fivem-respawn-nearby/tree/dev) branch and see if the problem persists? 

If the issue continues, I would still expect to see some errors in the in-game (F8) console to diagnose further.

Thanks,
Flamtky

**Comment by IzPogo** [comment]
Hello again @Flamtky 

I've just tried the dev branch but unfortunately, it still didn't work.
I do have these on my console now, hope they can be of help.

![Screenshot 2024-09-29 044519](https://github.com/user-attachments/assets/e59312f1-d713-4ab2-ba3d-d38708109d95)

**Comment by Flamtky** [comment]
Thanks for providing the console output. I can see the problem and have fixed it in the dev branch. It's likely that your server uses a different Lua version that "finds" the bug, whereas my version just ignores the missing parameters in the method call. 😂

Edit: I didn't test my solution, but think I fixed it!

**Comment by IzPogo** [comment]
Slightly good news and very unfortunate news, that error stopped appearing, but the respawn mechanic is still not working. No blips as well.

![Screenshot 2024-09-29 135011](https://github.com/user-attachments/assets/f642cb77-0b1d-4eb4-a2d2-727e4446df5e)
Only this part works for me, but the problem is I spawned in the random spawn points set in fivem-map-skater's map.lua so I guessed that was interfering, therefore I deleted the spawn points.

Then I got
![Screenshot 2024-09-29 122542](https://github.com/user-attachments/assets/d016f202-f7fb-4cbd-b283-8e084f08075b)
So I deleted map.lua along with the folder itself actually. No more error, literally. Everything went back to the same problem I was having in the first place where I'd spawn on the default backup point, but couldn't respawn and having no blips or debug prints.

I thought to myself, hey maybe basic-gamemode itself was interfering. I removed it, stopped it, changed setAutoSpawn to false, made this resource a gamemode again, to no avail.

My last resort now is to create and start a fresh new server and if that also doesn't work, I'm guessing this just wasn't made for me. Thank you for your time good fellow and may I return with good news.

**Comment by IzPogo** [comment]
Back after starting fresh and, things aren't looking so good. The same thing happened. F8 console did show the usual "Respawn called with coords: {x=0,y=0,z=0}" but respawn still not working 😔. Technically I did respawn but it was the normal random spawn points like default fivem. It's as if whatever's on the default resources kept overriding the spawning mechanics even tho technically setAutoSpawn should be false.

**Comment by Flamtky** [comment]
You are right, the `mapmanager` and `basic-gamemode` override the respawn logic. I'll add a note to the README to disable these resources. 

Did you try disabling `mapmanager` and `basic-gamemode`? I think after stopping them, you need to rejoin the server. Also, ensure that `baseevents` is running on your server.

**Comment by IzPogo** [comment]
THANK YOU, THANK YOU, THANK YOU. After disabling both `mapmanager` and `basic-gamemode`, along with enabling `baseevents`, I finally got the resource to work.

![Screenshot 2024-09-30 001343](https://github.com/user-attachments/assets/f9a7ef16-6c5c-44ac-8afa-116bb949743a)
(Respawn also working correctly)

I should've tried disabling `mapmanager` before this but I didn't as I heard it might mess with something. As for `baseevents`, I didn't know it was a separate resource and was needed.

A very big apology for taking your precious time and a very big thanks again for helping me.

**Comment by Flamtky** [comment]
No problem. I initially thought that the baseevents resource was enabled and started by default. I have updated the README to clarify this for future users.
